In [2]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.data import load_market_data
from src.residuals import (
    rolling_pca_residuals,
    rolling_residual_spread
)

# Load Data

In [4]:
prices, stock_returns, hedge_returns = load_market_data()

print(stock_returns.shape)
stock_returns.tail()

(1939, 20)

Ticker,AAPL,MSFT,NVDA,GOOGL,META,JPM,BAC,GS,XOM,CVX,JNJ,PFE,WMT,COST,BA,CAT,KO,PEP,DIS,NFLX
Date,,,,,,,,,,,,,,,,,,,,
2026-09-15,-0.005224,-0.016403,0.005736,-0.012622,0.006971,0.006740,0.000841,-0.011918,0.025685,0.026394,0.003304,-0.006133,-0.009076,-0.019110,-0.002758,-0.000587,-0.001238,-0.006161,-0.019983,-0.030129
2026-09-16,0.003229,-0.013719,0.008154,-0.006116,0.004580,-0.010128,-0.027218,-0.039614,-0.035436,-0.028608,0.000299,-0.003267,-0.005458,-0.008443,-0.036864,-0.001047,-0.009469,-0.008561,0.005356,-0.019127
2026-09-17,0.013808,0.015195,0.025432,0.013008,0.013367,0.001118,0.004836,0.014382,-0.000306,0.000142,0.011000,0.006555,-0.006605,0.000213,-0.024559,0.020250,0.002162,-0.005062,-0.015329,-0.014396
2026-09-18,-0.002582,-0.007976,0.013358,0.006363,-0.024270,0.001031,-0.007735,-0.009953,0.001654,-0.009737,-0.000851,0.000724,-0.000562,0.001544,0.006091,0.013048,0.002158,-0.029253,-0.025439,-0.046740
2026-09-21,0.008479,0.015857,0.022990,0.015535,0.114285,0.006778,0.003984,0.018461,-0.032041,-0.027875,-0.001926,0.002892,0.006652,0.003541,0.014884,0.009283,-0.012805,-0.001233,0.015194,0.021869

# Rolling PCA residuals

In [5]:
residuals = rolling_pca_residuals(
    stock_returns,
    pca_window=252,
    k=6
)

residuals.tail()

Ticker,AAPL,MSFT,NVDA,GOOGL,META,JPM,BAC,GS,XOM,CVX,JNJ,PFE,WMT,COST,BA,CAT,KO,PEP,DIS,NFLX
Date,,,,,,,,,,,,,,,,,,,,
2026-09-15,0.001337,-0.005716,0.007532,0.001980,0.001383,0.004545,-0.001637,-0.012227,0.008460,0.010667,0.007291,0.001028,-0.001212,-0.012813,0.020881,-0.003312,0.004319,0.000918,-0.007796,-0.003680
2026-09-16,0.016828,-0.001608,0.005424,-0.013092,-0.002792,0.015950,-0.003047,-0.012276,-0.017932,-0.012567,0.003583,0.009047,-0.002001,-0.003680,-0.026298,0.002551,-0.006530,-0.001679,0.024903,-0.002797
2026-09-17,0.014292,0.015146,0.002764,0.006164,-0.001592,-0.002771,0.002142,0.004027,-0.004227,-0.003400,0.014719,0.009457,0.000269,0.006798,-0.019345,0.000836,0.008274,0.002314,-0.012802,-0.008127
2026-09-18,0.005760,0.003071,0.008066,0.012385,-0.001815,0.006861,-0.001203,-0.012005,0.012214,0.000213,0.002959,0.008616,0.004400,0.009331,0.006749,-0.005641,0.010041,-0.018245,-0.008824,-0.009416
2026-09-21,-0.004682,0.001558,-0.004345,-0.024527,0.006500,-0.001029,-0.006950,0.007145,-0.006540,-0.005433,0.001665,0.001233,0.007477,0.006260,-0.002479,0.008336,-0.011447,-0.002587,0.000621,0.011067

# 20-day residual spread

In [6]:
spreads = rolling_residual_spread(
    residuals,
    window=20
)

spreads.tail()

Ticker,AAPL,MSFT,NVDA,GOOGL,META,JPM,BAC,GS,XOM,CVX,JNJ,PFE,WMT,COST,BA,CAT,KO,PEP,DIS,NFLX
Date,,,,,,,,,,,,,,,,,,,,
2026-09-15,0.066699,-0.007759,-0.022943,-0.014685,0.010610,-0.003192,-0.068542,-0.004821,-0.010468,0.026713,0.004163,0.032248,-0.027818,-0.054288,0.000488,0.017011,-0.012695,-0.024748,0.039560,0.001646
2026-09-16,0.072735,-0.007521,-0.026126,-0.046449,0.017452,0.005515,-0.076668,-0.022623,-0.032023,0.018898,-0.013065,0.038193,-0.027257,-0.053572,-0.015026,0.036386,-0.022897,-0.023229,0.070460,0.006290
2026-09-17,0.072647,0.013410,-0.029664,-0.035902,0.016183,0.013824,-0.060059,-0.017048,-0.028139,0.009531,0.001787,0.018687,-0.011862,-0.032423,-0.026537,0.035236,-0.017615,-0.024688,0.039494,0.003005
2026-09-18,0.079354,0.032327,-0.001598,-0.021624,0.013842,0.020139,-0.056434,-0.025740,-0.013439,0.021041,0.014274,0.024367,0.062546,-0.012611,-0.018918,0.014055,-0.021135,-0.057707,0.004970,-0.012524
2026-09-21,0.087373,0.023844,0.004661,-0.050320,0.019104,0.027289,-0.052400,-0.045264,-0.014147,0.016736,0.010354,0.020956,0.076523,-0.018330,-0.009044,0.022112,-0.036259,-0.066487,0.006479,-0.000244